### PR TITLE
Fix bugs in thread::scope()

### LINKED ISSUE #6: Document what happens when internal thread panics when joined
It is currently undocumented what happens when joining a panic-ed thread with [ScopedJoinHandle::join](https://docs.rs/crossbeam-utils/0.2.2/crossbeam_utils/scoped/struct.ScopedJoinHandle.html#method.join).

[`std::thread::JoinHandle::join`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.join) returns `-> Result<T>` instead of `-> T`, which returns the result of the panic.

BTW, I think automatically panicing is fine behavior.

### LINKED ISSUE #8: Document what happens when an un-joined scoped thread panics
This is related to #6 , but not identical. The problem is to know what happens when a scoped thread panics, but the user did _not_ explicitly join it.

### PR DESCRIPTION
**Pull request by jeehoonkang**
This PR fixes some bugs in `crossbeam_utils::thread` that @stjepang mentioned in #7.

- If a scoped thread panics, [other threads are not joined at all](https://github.com/crossbeam-rs/crossbeam-utils/pull/7#discussion_r168954812).
  I guaranteed that [all threads are joined](https://github.com/crossbeam-rs/crossbeam-utils/compare/master...jeehoonkang:thread?expand=1#diff-3e97dcab09523f9702269d7b101efbcbR260).

- [Panic should be propagated](https://github.com/crossbeam-rs/crossbeam-utils/pull/7#issuecomment-366524989).
  I think it's a little bit subtle.  In `std::thread` and `crossbeam_utils::thread`, when a spawned thread panics, `join()` returns `Err` and does not propagate panics.  I think the same thing should happen at the end of a `scope`: returning `Result` rather than propagating `panic`.  It is a **breaking change**, but anyway I'm throwing it away...  

Closes #6 
Closes #8

### CODE REVIEW

File: src/thread.rs [hunk 1]
```diff
@@ -214,14 +221,10 @@ pub struct ScopedJoinHandle<'a, T: 'a> {
 /// crossbeam_utils::thread::scope(|scope| {
 ///     scope.defer(|| println!("Exiting scope"));
 ///     scope.spawn(|| println!("Running child thread in scope"))
-/// });
-/// // Prints messages in the reverse order written
```
Comment (stjepang) [inline src/thread.rs]: Is this not true anymore?

Comment (jeehoonkang) [reply src/thread.rs]: It's true actually, but the methods spec doesn't guarantee it.  On the contrary to what is commented before, there's no order between joining spawned threads and running deferred functions.  I just removed the comment, effectively leave the order unspecified.

Definitely, we need to discuss what's the desired specification.  Asking the same question you raised before, what's the purpose of `defer()`?  What do we expect from it?  I think need to answer those questions before releasing a new version.  Of course we have to write tests (#12).

Comment (stjepang) [reply src/thread.rs]: This is the only use of `defer` I could find:
https://github.com/wayslog/statsd/blob/f27113df8667407b247d0ff6e63396a54c612e76/src/sender/mod.rs#L18

But looks like it's not necessary at all - calls to `.join()` can be invoked without `defer` as well.

I guess `defer` is actually useless and the same effect can be achieved using [`scopeguard::defer!`](https://docs.rs/scopeguard/0.3.3/scopeguard/macro.defer.html) anyway. So my suggestion would be to remove it.
